import React from 'react'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import logoDark from '../../../public/assets/logos/logoLight.png'
import style from './Navbar.module.css'

export default function Navbar() {
    return (<>
        <Head>
            <title>Coté Design</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            <link
                href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
                rel="stylesheet"
                integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
                crossOrigin="anonymous"
            />
        </Head>
        <div className={style.navbar}>
            <nav className='navbar navbar-dark bg-dark'>
                <div className="container-fluid justify-content-center">
                <Link className='navbar-brand mx-4' href={'/'}>
                     <Image src={logoDark} width="150" height="60"/>
                        </Link>

                    <Link className='navbar-brand mx-4' href={'/accueil'}>
                        Accueil
                    </Link>
                    <Link className='navbar-brand mx-4' href={'/services'}>
                        Services
                    </Link>
                    <Link className='navbar-brand mx-4' href={'/contact'}>
                        Contact
                    </Link>
                </div>
            </nav>
        </div>
    </>
    )
}
