import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import logo from '../../public/assets/logos/logoLight.png'
import logo2 from '../../public/assets/logos/logoDark.png'
import styles from '@/styles/Accueil.module.css'
import { useTranslation } from 'react-i18next';

  
  export default function accueil(props) {
   
  const { t } = useTranslation();
  return (
    <>
     <Head>
        <title>Coté Design Beta</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        
      <main className={styles.main}>
        <h1>{t ("accueil.version")}</h1>
        <p>{t ("accueil.prez")}</p>
        <p>{t ("accueil.prez2")}</p>
        <p>{t ("accueil.thanks")}</p>
      </main>
       
    </>
  )
}
