import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import img1 from '../../public/assets/logos/logo-accueil.jpeg'
import flagFr from '../../public/assets/icones/flag-fr.gif'
import flagEng from '../../public/assets/icones/flag-eng.gif'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Coté Design Beta</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.logoContainer}>
          <div className={styles.logo}>
            <div className="logo"><Image src={img1} width="450" height="100" /></div>
            <div className={styles.textLogo}>ARCHITECTURE & MISE EN OEUVRE</div>
            <div className={styles.flagContainer}>
              <div className="flag-french">
                <Link href={'accueil'}>
                  <Image src={flagFr} width="60" height="40" />
                  <br></br> Français
                </Link>
              </div>
              <div className="flag-english">
              <Link className='navbar-brand mx-4' href={'/'}>
                <Image src={flagEng} width="60" height="40" />
                <br></br> English
                    </Link>
              </div>
            </div>
          </div>
        </div>
        <h1>Bienvenue sur coté Design</h1>
      </main>
    </>
  )
}
